### ISSUE TITLE
Block Explorer not working on devnet test

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/filecoin-explorer#8]
![Screen Shot 2019-03-22 at 4 34 15 PM](https://user-images.githubusercontent.com/5515260/54851464-5bdaab80-4cc0-11e9-964f-bd7c71350747.png)

Right now when I go to http://test.kittyhawk.wtf:8010/ and click the Block Explorer tab I get this.

**Comment by travisperson** [comment]
This ended up being mostly a bug on the `go-filecoin` side (https://github.com/filecoin-project/go-filecoin/pull/2396). However, we recently did change the encoding of some values, so I've opened a PR to fix those as well (#10)
